version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway
    container_name: gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
      - gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:6541/shareit

  db:
    image: postgres
    restart: always
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "shareit"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"